# Generated by Django 5.0.6 on 2024-07-21 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_payment_link_alter_payment_session_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_sum',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='сумма оплаты'),
        ),
    ]
