# Generated by Django 5.0.6 on 2024-07-04 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='ссылка'),
        ),
    ]
