# Generated by Django 5.0.6 on 2024-07-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_course_author_lesson_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='url',
            field=models.URLField(verbose_name='ссылка'),
        ),
    ]
